apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: unimall
  creationTimestamp: "2021-10-04T10:32:17Z"
  generation: 1
  labels:
    k8s-app: unimall
    qcloud-app: unimall
  managedFields:
    - apiVersion: apps/v1
      manager: tke-apiserver
      operation: Update
      time: "2021-10-04T10:32:17Z"
    - apiVersion: apps/v1
      manager: kube-controller-manager
      operation: Update
      time: "2021-10-04T10:32:20Z"
  name: unimall
  namespace: dobbin
  selfLink: /apis/apps/v1/namespaces/dobbin/deployments/unimall
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: unimall
      qcloud-app: unimall
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: unimall
        qcloud-app: unimall
    spec:
      containers:
        - image: ${IMAGE}
          imagePullPolicy: Always
          name: unimall
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ping
              port: 8081
              scheme: HTTP
            periodSeconds: 1
            initialDelaySeconds: 180
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 36
            httpGet:
              path: /health/ping
              port: 8081
              scheme: HTTP
            periodSeconds: 5
            initialDelaySeconds: 15
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 500m
              memory: 810Mi
            requests:
              cpu: 300m
              memory: 512Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliyun
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: k8s-app
                    operator: In
                    values:
                      - unimall
              topologyKey: kubernetes.io/hostname
