---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-dobbin-unimall-sc
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: svc-dobbin-unimall
  namespace: dobbin
  labels:
    app: svc-dobbin-unimall
  annotations:
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    k8s-app: unimall
    qcloud-app: unimall
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: mall
  labels:
    k8s-app: unimall
    qcloud-app: unimall
  name: unimall
  namespace: dobbin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: unimall
      qcloud-app: unimall
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: unimall
        qcloud-app: unimall
    spec:
      containers:
        - image: ${IMAGE}
          imagePullPolicy: Always
          name: unimall
          resources:
            limits:
              cpu: 150m
              memory: 1124Mi
            requests:
              cpu: 150m
              memory: 1124Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: dobbin-unimall-log
              mountPath: "/home/dobbin/logs"
      volumes:
        - name: dobbin-unimall-log
          persistentVolumeClaim:
            claimName: pvc-dobbin-unimall-sc
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliyun
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30