server:
  port: ${UNIMALL_PORT:8000}
  servlet:
    context-path: /unimall


spring:
  application:
    name: unimall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5
    password: ${UNIMALL_DB_PASSWORD:8000}
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${UNIMALL_DB_HOST:localhost}/${UNIMALL_DB_PORT:3306}?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root

  redis:
    master-name: mymaster
    mode: single
    database: ${UNIMALL_REDIS_DATABASE:0}
    host: ${UNIMALL_REDIS_HOST:localhost}:${UNIMALL_REDIS_PORT:6379}
  user-redis:
    database: ${UNIMALL_REDIS_DATABASE:0}
    host: ${UNIMALL_REDIS_HOST:localhost}:${UNIMALL_REDIS_PORT:6379}
  lock-redis:
    database: ${UNIMALL_REDIS_DATABASE:0}
    host: ${UNIMALL_REDIS_HOST:localhost}:${UNIMALL_REDIS_PORT:6379}

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: unimall_
  mapper-locations: classpath:/mapper/**/*.xml

com:
  dobbinsoft:
    db:
      # 类自动生成表结构
      auto-build-table: false
    system:
      admin-session-period: 43200
      user-session-period: 43200
      mutex-login: true # 是否允许同一个账户多地登录
    oss:
      enable: ${UNIMALL_OSS_ENABLE:mock}
      ali-access-key-id: ${UNIMALL_OSS_ALI_ACCESS_KEY_ID:xxx}
      ali-access-key-secret: ${UNIMALL_OSS_ALI_ACCESS_KEY_SECRET:xxx}
      ali-endpoint: ${UNIMALL_OSS_ALI_ENDPOINT:xxx}
      ali-bucket: ${UNIMALL_OSS_ALI_BUCKET:xxx}
      ali-base-url: ${UNIMALL_OSS_ALI_BASE_URL:xxx}
    sms:
      enable: ${UNIMALL_SMS_ENABLE:mock}
      aliyun-access-key-id: ${UNIMALL_SMS_ALI_ACCESS_KEY_ID:xxx}
      aliyun-access-key-secret: ${UNIMALL_SMS_ALI_ACCESS_KEY_SECRET:xxx}
      aliyun-signature: ${UNIMALL_SMS_ALI_SIGNATURE:xxx}
      aliyun-register-template-id: ${UNIMALL_SMS_TEMPLATE_ID:xxx}
      aliyun-bind-phone-template-id: ${UNIMALL_SMS_TEMPLATE_ID:xxx}
      aliyun-reset-password-template-id: ${UNIMALL_SMS_TEMPLATE_ID:xxx}
      aliyun-admin-login-template-id: ${UNIMALL_SMS_TEMPLATE_ID:xxx}

    admin-notify:
      enable: mock
    advert:
      top-sales-num: 10
    order:
      auto-confirm-time: 259200
      auto-cancel-time: 900
    wx-app:
      app-id: ${UNIMALL_APP_ID:xxx}
      app-secret: ${UNIMALL_APP_SECRET:xxx}
      mini-app-id: ${UNIMALL_MINI_APP_ID:xxx}
      mini-app-secret: ${UNIMALL_MINI_APP_SECRET:xxx}
      h5-app-id: ${UNIMALL_H5_APP_ID:xxx}
      h5-app-secret: ${UNIMALL_H5_APP_SECRET:xxx}
    wx-pay:
      mch-id: ${UNIMALL_WX_PAY_MCH_ID:xxx}
      mch-key: ${UNIMALL_WX_PAY_MCH_KEY:xxx}
      key-path: ${UNIMALL_WX_PAY_KEY_PATH:/home/dobbin/cert/application.p12}
      notify-url: ${UNIMALL_WX_NOTIFY_URL:https://unimallv4.dobbinsoft.com/unimall/cb/pay}
    ali-app:
      ali-gateway: https://openapi.alipay.com/gateway.do
      app-id: 2021004150664371
      app-private-key2: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC+Hcw44KismUFBY5Vt0oiAny8A/9TRsdwRBwvWz+C8QpCQlMKiLcFFzvNO5To/IZCMq88lFFUbCB/6FQ1ngmVhHT32XSZVY2jt5QKfdLyc6+320ZfmzhIcbmHr5gxx63gHDQ4Bn6nCz81c/Qd/m2DD523U7CgVshlbjcpl6uUG+IgdApaleczM5ITPzQscidRIScoD1O5mA+KqaCC1tjX0qoiUeIarbVyoUn+arznbVkgcPrAqtPW2ipjoFr35T4BArGlIA9auo0A8tkGTJX3Os44qRH+JCiwvzbawfhgm5Ss6cWZ1o6Y772TymmPQv3ZBhw4x1+cG1sQHGA7IwtGJAgMBAAECggEARDBH2XaqyQ1G3H8tT3CdyRRPNZqM6JFUjz7pvihdQOjXFSRmEuk6UyGBHyEUnSQaxnmxGGmMhN+LKJV4c1HPrt9gJAcRArtfHURwhmTGabotZcOTKhNrZ4sn0AZ5HDsKl+zUwzxTFS6XR+zxTZGbSWiuehoh3nY8phvbJmbzsmW/lTiwm0llZj5EiPT6ayam7CE8GZszNJmJpDNSIb65kv9iaadu56C/iqVLoSt3lxutCfYCE2SJ7Bb+ZZxy/1dNPJNtPLzBy84DSxCvkPHgyncrzJ4m7oaHZ3stcwb/42XpsrKLi1NvlvtQ3jqm1iXmKoQHD/3NYycRy2ac08lJSQKBgQDgULQRyamA4Q64I1Mn3CxuTSvujMxHTxnhnbfWqHDBk69nvyGT3FlfukpXSm5nTgANAkbhZsruUrsGV/x/IVqwNCkHVdbPLb1vIHy0bP6QXd32qAit6VY/BhBMPQvoDniL6zXjnM2KbakJC87VAhKrKvjrtVs49Z6CD86KeHFKYwKBgQDY+HSHpZ7ujBCUa4zdyGbJFDqsA+zfSdTfjV1BADb6KjYelBrvEprkFWHZ9bHiAsUTgZ2WbDFT5u0wtom3qzanA3dywnleRov0mkaMU0osUhnPJDPlLSitTI/9q8pUDXhk7Y+QX/WNJy2B+xnUXojv8Cx9+Bau4nMUZMHm0/GiIwKBgQDWbG7lPgd4+inu3V2lEbOrMLvZCeBQHg4YfIJ6gINgl8MpgiwfwpfwiQx9StokiAxGYzHMT02W6aB8HOlxwTmGjCXYLDbtzsRxkPWEJ1hkOkZufQvm6tEV5772kbhq+EJFRe86h+528AKQcighuByOYMKX1sG/vhLqMx/1f9KUDwKBgQDQ46ONVS8Gi2MLAeDFRcNvpEI4ii7rarG/6OH3SrWjdDBWkFC+CzOEk/F5Xsq7xd7nQMrvn4p+NL33QEamxfgAI55EpmcjFNh5zm5Ne4LV2NVwUHKGGkwnTKb0mwhYk/9tbCnj3f8Svr1Zft8HT1yXZKvxO4DbLrmM0NS93x+r8QKBgQCxFElDHymRB9SJ1y/T/jnOPnhI6iG8vdX5PYbEFmKiOPfFSWYPBs+GrXeDOawOSF+8korXuFOcps7EZLoBmjpWMoUmV8Sdh+2ZLIX7M250FfKNuKXidJPQabp14jCxynjCsorMTV5h/78kDL/46sVlJbM9BtZ0ojRRw4Eg53WuOg==
